POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email":"levy310898@gmail.com",
  "password":"peevy001",
  "name":"le vy"
}

###

POST http://localhost:5000/api/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjExZmYwMWU0MTUxNDEyMDUyNTkzNzI0IiwidXNlciI6ImxlIHZ5In0sImlhdCI6MTYyOTUzNDQzMiwiZXhwIjoxNjI5NjIwODMyfQ.euJIzZ9B4BtRNW0CrWJCIjpckHP2Xw5nLwszF55ukXs

{
  "title":"title 2",
  "description":"something to test"
}

###

GET http://localhost:5000/api/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjExZmYwMWU0MTUxNDEyMDUyNTkzNzI0IiwidXNlciI6ImxlIHZ5In0sImlhdCI6MTYyOTUzNDQzMiwiZXhwIjoxNjI5NjIwODMyfQ.euJIzZ9B4BtRNW0CrWJCIjpckHP2Xw5nLwszF55ukXs

###

PUT  http://localhost:5000/api/project/6120bb4726075a57dc819c7a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjExZmYwMWU0MTUxNDEyMDUyNTkzNzI0IiwidXNlciI6ImxlIHZ5In0sImlhdCI6MTYyOTUzNDQzMiwiZXhwIjoxNjI5NjIwODMyfQ.euJIzZ9B4BtRNW0CrWJCIjpckHP2Xw5nLwszF55ukXs

{
  "title":"title 5",
  "description":"Update description"
}

###

DELETE http://localhost:5000/api/project/61211406a263822660ba2958
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjExZmYwMWU0MTUxNDEyMDUyNTkzNzI0IiwidXNlciI6ImxlIHZ5In0sImlhdCI6MTYyOTUzNDQzMiwiZXhwIjoxNjI5NjIwODMyfQ.euJIzZ9B4BtRNW0CrWJCIjpckHP2Xw5nLwszF55ukXs
